### ISSUE TITLE
Spline Mesh works in wrong coordinate system

### ISSUE THREAD

**Issue by RobertAcksel** [benoit-dumas/SplineMesh#12]
unity uses Z as the forward axis but spline mesh works using the x axis as the forward axis.
this is the case in the examples but also in core code like MeshBender.

**Comment by RobertAcksel** [comment]
I got convinced that the default axis should be x to bend meshes along. however it is not so difficult to add an option to choose the axis to bend along.
Closing it as it is not a real issue but rather an design decision.

**Comment by benoit-dumas** [comment]
Yes we could add a property in the mesh bender to allow the user to choose the forward axis. There is such property in SplineMesh from Unreal Engine 4.

Feel free to send a pull request, I would gladly integrate it.
