### ISSUE TITLE
can't edit node values in the inspector

### ISSUE THREAD

**Issue by mega-egg** [benoit-dumas/SplineMesh#30]
when trying to input in or drag the individual node fields, the value seems to change for about 1 frame (visible only in the spline/extrusion shape, not in the actual field), before reverting back to default immediately. editing direction/position/up vector using the handles works as expected.

i dug around in the code a bit but could not find the cause. i put a debug line in one of the property setters and it looks like it's being called correctly when editing the value, but not when it reverts back to default, which might point to a problem with serialization?

using unity 2018.3.14f1 on windows 10 (x64), tried with both the asset store version and the code in this repository.

thank you!

**Comment by benoit-dumas** [comment]
Solved, thanks for the report !

**Comment by mega-egg** [comment]
thank you so much!

**Comment by benoit-dumas** [comment]
my pleasure ! if you like SplineMesh, please write a short review on the asset store !
