### ISSUE TITLE
Editor code preventing compilation to standalone player

### ISSUE THREAD

**Issue by LiorBanai** [benoit-dumas/SplineMesh#40]
the ```SplineEditor.cs``` and ```SplineExtrusionEditor.cs```  are editor related code that prevent compilation  to standalone player.

I have added  ```#if UNITY_EDITOR``` and ```#endif``` and it seems to works.
It may be good idea to add it to here also?

**Comment by benoit-dumas** [comment]
The correct way to do this is to place these files in a folder named
Editor. All Editor folders are ignored by Unity upon build.

It's not normal that you have the error. Have you moved the files?

Le mar. 22 déc. 2020 à 18:43, Lior Banai <notifications@github.com> a
écrit :

**Comment by LiorBanai** [comment]
I put the code in new Assembly definition and the Editor folder is in "Scripts\Editor" folder.
Maybe the Editor folder needs to be top level folder?

**Comment by benoit-dumas** [comment]
Nope, any Editor folder should be ignored upon build :
https://docs.unity3d.com/Manual/SpecialFolders.html

Le mar. 22 déc. 2020 à 20:27, Lior Banai <notifications@github.com> a
écrit :

**Comment by LiorBanai** [comment]
Strange. Thanks, I'll investigate it more. Closing this :)
