### ISSUE TITLE
Does this tool support ingame editing ?

### ISSUE THREAD

**Issue by suprafun** [benoit-dumas/SplineMesh#9]
Hello, I am new to Unity and am wondering if this editing tool support in game editing ? Thank-you.

**Comment by benoit-dumas** [comment]
SplineMesh is using the observer pattern so yes, the edition of the bézier curves is working in play mode the exact same way than in edit mode, thanks to the RunInEditor attribute.

Note that you will need to subscribe to spline or nodes events to update mesh coliders as they are computed only once at game start.
